<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Phone, Search } from '@element-plus/icons-vue'
import { api } from '@/api/client'

interface LateReturn {id:number;studentNo:string;studentName:string;room:string;returnDate:string;expectedTime:string;reason:string;contact:string;status:string;createdAt:string}
const records=ref<LateReturn[]>([]),loading=ref(true),keyword=ref(''),status=ref('全部状态')
const filtered=computed(()=>records.value.filter(item=>(status.value==='全部状态'||item.status===status.value)&&`${item.studentName}${item.studentNo}${item.room}`.includes(keyword.value)))
async function load(){loading.value=true;try{records.value=await api.get<LateReturn[]>('/api/admin/late-returns')}finally{loading.value=false}}
async function update(item:LateReturn,next:string){try{await api.patch(`/api/admin/late-returns/${item.id}/status`,{status:next});ElMessage.success(next==='已联系'?'已记录联系状态':'晚归记录已确认');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'处理失败')}}
onMounted(load)
</script>
<template><div><div class="page-heading"><div><h1>晚归管理</h1><p>查看学生晚归登记，及时联系并确认学生安全。</p></div><div class="today">今日待确认 <strong>{{records.filter(i=>i.status==='待确认').length}}</strong> 人</div></div><section class="summary"><div><span>今日登记</span><strong>{{records.filter(i=>i.returnDate==='2026-09-10').length}}</strong><small>人</small></div><div><span>待确认</span><strong class="orange">{{records.filter(i=>i.status==='待确认').length}}</strong><small>人</small></div><div><span>已联系</span><strong class="blue">{{records.filter(i=>i.status==='已联系').length}}</strong><small>人</small></div><div><span>已确认</span><strong class="green">{{records.filter(i=>i.status==='已确认').length}}</strong><small>人</small></div></section><section class="panel"><div class="filter-bar"><div class="search-box"><el-icon><Search/></el-icon><input v-model="keyword" class="filter-input" placeholder="搜索姓名、学号或宿舍"/></div><select v-model="status" class="filter-input select"><option>全部状态</option><option>待确认</option><option>已联系</option><option>已确认</option></select></div><div v-loading="loading" class="table-wrap"><table class="data-table"><thead><tr><th>学生</th><th>宿舍</th><th>晚归日期</th><th>预计返回</th><th>晚归原因</th><th>联系电话</th><th>状态</th><th>处理</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id"><td><div class="student"><i>{{item.studentName.slice(-1)}}</i><span><b>{{item.studentName}}</b><small>{{item.studentNo}}</small></span></div></td><td class="table-primary">{{item.room}}</td><td>{{item.returnDate}}</td><td><strong class="time">{{item.expectedTime}}</strong></td><td><span class="reason" :title="item.reason">{{item.reason}}</span></td><td><button class="phone" @click="update(item,'已联系')"><el-icon><Phone/></el-icon>{{item.contact}}</button></td><td><span class="status-pill" :class="item.status==='已确认'?'status-success':item.status==='已联系'?'status-info':'status-warning'">{{item.status}}</span></td><td><button v-if="item.status!=='已确认'" class="confirm" @click="update(item,'已确认')">确认返回</button><span v-else class="handled">已处理</span></td></tr><tr v-if="!loading&&!filtered.length"><td colspan="8" class="empty">暂无符合条件的记录</td></tr></tbody></table></div><div class="pagination"><span>共 {{filtered.length}} 条数据</span><div class="page-buttons"><button>‹</button><button class="active">1</button><button>›</button></div></div></section></div></template>
<style scoped>.today{padding:9px 13px;border:1px solid #f0ddbc;border-radius:8px;color:#9a743b;background:#fff9ed;font-size:10px}.today strong{margin:0 3px;color:#bb7026;font-size:15px}.summary{margin-bottom:17px;display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.summary>div{padding:17px 19px;border:1px solid var(--line);border-radius:11px;background:white}.summary span{display:block;margin-bottom:7px;color:#7d8986;font-size:9px}.summary strong{font-size:23px}.summary small{margin-left:4px;color:#9ca6a3;font-size:8px}.orange{color:#bd7823}.blue{color:#557dac}.green{color:#187b6c}.search-box{position:relative}.search-box .el-icon{position:absolute;z-index:1;left:11px;top:10px;color:#93a09c}.search-box input{padding-left:33px}.filter-input.select{width:140px}.student{display:flex;align-items:center;gap:8px}.student>i{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;color:#1b756c;background:#e6f4f1;font-style:normal;font-weight:600}.student span{display:grid;gap:2px}.student b{font-size:10px}.student small{color:#929d99;font-size:8px}.time{color:#b16728}.reason{display:block;max-width:180px;overflow:hidden;text-overflow:ellipsis}.phone{padding:0;border:0;display:flex;align-items:center;gap:4px;color:#4d746d;background:transparent;font-size:9px}.confirm{height:28px;padding:0 9px;border:0;border-radius:6px;color:white;background:#13796f;font-size:9px}.handled{color:#9aa5a2;font-size:9px}.empty{text-align:center!important;padding:45px!important;color:#949f9c!important}@media(max-width:650px){.summary{grid-template-columns:1fr 1fr}.filter-input.select{width:100%}}</style>
