<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Bell, Search, Warning } from '@element-plus/icons-vue'
import { api } from '@/api/client'
interface Notice{id:number;title:string;summary:string;category:string;publishedAt:string;important:boolean;read:boolean}
const notices=ref<Notice[]>([]),keyword=ref(''),active=ref('全部')
const filtered=computed(()=>notices.value.filter(i=>(active.value==='全部'||i.category===active.value)&&`${i.title}${i.summary}`.includes(keyword.value)))
async function load(){notices.value=await api.get<Notice[]>('/api/student/notices')}
async function open(item:Notice){if(!item.read){await api.patch(`/api/student/notices/${item.id}/read`);item.read=true}ElMessage.info(item.summary)}
onMounted(load)
</script>
<template><div><div class="student-page-head"><span>CAMPUS NOTICE</span><h1>通知公告</h1><p>及时了解宿舍管理、安全提醒和校园活动。</p></div><section class="notice-layout"><aside><div class="search"><el-icon><Search/></el-icon><input v-model="keyword" placeholder="搜索通知"/></div><button v-for="tab in ['全部','安全通知','生活服务','校园活动']" :key="tab" :class="{active:active===tab}" @click="active=tab">{{tab}}<b v-if="tab==='全部'">{{notices.length}}</b></button></aside><main class="notice-list"><article v-for="item in filtered" :key="item.id" :class="{unread:!item.read}" @click="open(item)"><div class="notice-icon" :class="{important:item.important}"><el-icon><Warning v-if="item.important"/><Bell v-else/></el-icon></div><div><span>{{item.category}} · {{item.publishedAt}}</span><h2>{{item.title}}<i v-if="!item.read"/></h2><p>{{item.summary}}</p></div><b>→</b></article><div v-if="!filtered.length" class="empty">没有找到相关通知</div></main></section></div></template>
<style scoped>.student-page-head{margin-bottom:22px}.student-page-head>span{color:#198075;font-size:8px;letter-spacing:1.4px}.student-page-head h1{margin:5px 0;font-size:25px}.student-page-head p{margin:0;color:#82908c;font-size:11px}.notice-layout{display:grid;grid-template-columns:190px 1fr;gap:16px}.notice-layout>aside{height:max-content;padding:10px;border:1px solid #e1e7e4;border-radius:13px;display:grid;background:white}.search{height:35px;margin-bottom:8px;padding:0 9px;border:1px solid #e1e6e4;border-radius:7px;display:flex;align-items:center;gap:6px;color:#93a09c}.search input{min-width:0;width:100%;border:0;outline:0;font-size:9px}.notice-layout aside>button{height:40px;padding:0 10px;border:0;border-radius:7px;display:flex;justify-content:space-between;align-items:center;color:#6f7d79;background:transparent;font-size:10px}.notice-layout aside>button.active{color:#14766c;background:#eaf6f3;font-weight:600}.notice-layout aside b{font-size:8px}.notice-list{display:grid;gap:10px}.notice-list article{min-height:100px;padding:17px;border:1px solid #e1e7e4;border-radius:13px;display:grid;grid-template-columns:40px 1fr 20px;align-items:center;gap:14px;background:white;cursor:pointer;transition:.2s}.notice-list article:hover{transform:translateY(-1px);box-shadow:0 7px 18px rgba(30,70,61,.06)}.notice-list article.unread{border-left:3px solid #1a887b}.notice-icon{width:39px;height:39px;border-radius:10px;display:grid;place-items:center;color:#347b70;background:#e9f5f2}.notice-icon.important{color:#c26c35;background:#fff1e5}.notice-list article>div:nth-child(2){min-width:0}.notice-list span{color:#8b9793;font-size:8px}.notice-list h2{margin:6px 0 5px;font-size:12px}.notice-list h2 i{display:inline-block;width:5px;height:5px;margin-left:6px;border-radius:50%;background:#ec705e;vertical-align:top}.notice-list p{margin:0;color:#7c8985;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.notice-list article>b{color:#9da7a4}.empty{padding:70px;text-align:center;color:#909c98;font-size:10px}@media(max-width:650px){.notice-layout{grid-template-columns:1fr}.notice-layout>aside{display:flex;overflow-x:auto}.search{min-width:150px;margin:0 8px 0 0}.notice-layout aside>button{min-width:75px}.notice-list p{white-space:normal;line-height:1.6}}</style>
