<script setup lang="ts">
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Lock, Phone, User } from '@element-plus/icons-vue'
import { useAuthStore } from '@/stores/auth'
import ChangePasswordDialog from '@/components/ChangePasswordDialog.vue'
const auth=useAuthStore(),passwordDialog=ref<InstanceType<typeof ChangePasswordDialog>|null>(null)
</script>
<template><div><div class="student-page-head"><span>PROFILE</span><h1>个人中心</h1><p>管理个人资料与账号安全。</p></div><section class="profile-grid"><aside class="student-card identity"><div class="avatar">{{auth.user.initials}}</div><h2>{{auth.user.name}}</h2><span>{{auth.user.studentNo}}</span><b>计算机学院 · 软件工程</b><div><small>2024 级</small><small>本科在读</small></div></aside><main class="student-card"><header><h2>基本资料</h2><button @click="ElMessage.info('资料修改需要学校统一身份认证')">编辑资料</button></header><div class="info-grid"><label><span><el-icon><User/></el-icon>姓名</span><strong>{{auth.user.name}}</strong></label><label><span>学号</span><strong>{{auth.user.studentNo}}</strong></label><label><span><el-icon><Phone/></el-icon>联系电话</span><strong>187****4831</strong></label><label><span>所在宿舍</span><strong>松园1号楼 302</strong></label><label><span>紧急联系人</span><strong>陈先生 · 139****6682</strong></label><label><span>辅导员</span><strong>李老师</strong></label></div><div class="security"><h3>账号安全</h3><button @click="passwordDialog?.open()"><el-icon><Lock/></el-icon><span><strong>修改登录密码</strong><small>验证原密码后设置新密码</small></span><b>→</b></button></div></main></section><ChangePasswordDialog ref="passwordDialog"/></div></template>
<style scoped>.student-page-head{margin-bottom:22px}.student-page-head>span{color:#198075;font-size:8px;letter-spacing:1.4px}.student-page-head h1{margin:5px 0;font-size:25px}.student-page-head p{margin:0;color:#82908c;font-size:11px}.profile-grid{display:grid;grid-template-columns:260px 1fr;gap:17px}.student-card{border:1px solid #e1e7e4;border-radius:14px;background:white}.identity{height:max-content;padding:30px;display:flex;align-items:center;flex-direction:column;text-align:center}.avatar{width:72px;height:72px;border-radius:50%;display:grid;place-items:center;color:white;background:linear-gradient(140deg,#1c8b7e,#62bdad);font-size:24px;font-weight:600}.identity h2{margin:15px 0 4px;font-size:17px}.identity>span{color:#84918d;font-size:9px}.identity>b{margin:16px 0;color:#65736f;font-size:10px;font-weight:500}.identity>div:last-child{padding-top:15px;border-top:1px solid #edf0ef;display:flex;gap:8px}.identity small{padding:4px 7px;border-radius:5px;color:#44736b;background:#eef6f4;font-size:8px}.profile-grid main>header{height:62px;padding:0 21px;border-bottom:1px solid #edf0ef;display:flex;align-items:center;justify-content:space-between}.profile-grid main h2{font-size:14px}.profile-grid main header button{border:0;color:#15766c;background:transparent;font-size:9px}.info-grid{padding:22px;display:grid;grid-template-columns:1fr 1fr;gap:22px}.info-grid label{display:grid;gap:6px}.info-grid span{display:flex;align-items:center;gap:5px;color:#899591;font-size:8px}.info-grid strong{font-size:11px;font-weight:500}.security{margin:0 22px 22px;padding-top:18px;border-top:1px solid #edf0ef}.security h3{font-size:11px}.security button{width:100%;padding:12px;border:1px solid #e5e9e7;border-radius:8px;display:flex;align-items:center;gap:10px;text-align:left;background:#fafbfb}.security button>.el-icon{color:#1b7b71}.security button>span{display:grid;gap:3px;flex:1}.security button strong{font-size:9px}.security button small{color:#8c9894;font-size:8px}.security button>b{color:#9ba5a2}@media(max-width:650px){.profile-grid{grid-template-columns:1fr}.info-grid{grid-template-columns:1fr}}</style>
